GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "test 4",
    "author": "test 3",
    "url": "test",
    "likes": 10
}

###